### ISSUE TITLE
Can you unify licenses?

### ISSUE THREAD

**Issue by nomaddo** [DexterInd/RFR_Tools#42]
I am getting troubles with licenses under `miscellaneous` directory.
https://github.com/DexterInd/RFR_Tools/tree/master/miscellaneous

- [setup.py](https://github.com/DexterInd/RFR_Tools/blob/master/miscellaneous/setup.py) : GPL-3
- [2C_mutex.py](https://github.com/DexterInd/RFR_Tools/blob/master/miscellaneous/I2C_mutex.py) : no license?
- [auto_detect_robot.py](https://github.com/DexterInd/RFR_Tools/blob/master/miscellaneous/auto_detect_robot.py) : no license?
- Other files have MIT license

I would be happy if you would unify such licenses.

**Comment by CleoQc** [comment]
Hello, and thanks for reaching out. 
Please consider everything as having an MIT license. 
I've updated a couple of files.
